### ISSUE TITLE
Forced effect locks order in DoomPioneerParkour

### ISSUE THREAD

**Issue by Mykybo** [WelkinU/OverwatchWorkshopScripts#3]
Would it be possible to add forced effect locks order in DoomPioneerParkour?

maybe make it optional in settings, but it would be great!!

**Comment by WelkinU** [comment]
Ok added the functionality to settings in commit 27d1ae6e22b8c40afc6f2429feaebe24e51204dc. I set it to be enabled by default. Code YMVCR also updated with this change.

![image](https://user-images.githubusercontent.com/47000850/114480988-9f6b1f80-9bd1-11eb-97f2-9b9b21d7e825.png)

**Comment by Mykybo** [comment]
Thanks a lot! works great, we are enjoying it :)
