### ISSUE TITLE
Doomfist Pioneer - if you load cps the mode is broken

### ISSUE THREAD

**Issue by Mykybo** [WelkinU/OverwatchWorkshopScripts#6]
In Doomfist Pioneer if you load saved cps and finish them all then you do not get "pioneer" and can't continue making more cps.

**Comment by WelkinU** [comment]
I think way in the past that was the way it worked, but someone actually made a suggestion that I change it to the current way. 

I added a Workshop Settings Toggle with default to allowing Pioneer in memory recall mode.

![image](https://user-images.githubusercontent.com/47000850/152698582-d21d7163-d583-49e8-b650-ccb1a60249bf.png)

**Comment by Mykybo** [comment]
i was using old version
